### ISSUE TITLE
run the code

### ISSUE THREAD

**Issue by arashakb** [nmndeep/robust-segmentation#3]
you can't run the code while the train.py is in the tools folder cause it can't find semseg. if i'm wrong, correct me please

**Comment by nmndeep** [comment]
Hi, 
Thanks for pointing this out. This seems to be an import error, I have updated the `train.py` with appending `cwd` to syspath. This should be solved now.

**Comment by steffen-jung** [comment]
Hi, the same issue exists in `infer.py`.
